FROM openjdk:17.0.1

ARG JAR_FILE
ARG DB_IP
ARG JWT_SECRET
ARG DB_USER
ARG DB_PASSWORD
ENV DB_IP=$DB_IP
ENV JWT_SECRET=$JWT_SECRET
ENV DB_USER=$DB_USER
ENV DB_PASSWORD=$DB_PASSWORD

COPY $JAR_FILE app.jar

ENTRYPOINT ["java","-jar","/app.jar"]