name: Build and push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

env:
  IMAGE_NAME: 'pastestorage'
  JAR_NAME: 'pastestorage-0.0.1-SNAPSHOT.jar'
  DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
  DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
  DB_IP: ${{ vars.DB_IP }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          build-args: |
            JAR_FILE=./build/libs/${{ env.JAR_NAME }}
            DB_IP=${{ env.DB_IP }}
            JWT_SECRET=${{ env.JWT_SECRET }}
          push: true
          tags: ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest